modLoader="javafml"
loaderVersion="[11,)"
license="LGPL-3.0-only"

[[mods]]
modId="lumin_graphics_mc"
version="1.0.0+mc26.2"
displayName="Lumin Graphics MC"
description='''Minecraft-owned rendering context bridge for Lumin Graphics.'''
displayTest="IGNORE_SERVER_VERSION"

[features.lumin_graphics_mc]
javaVersion="[25,)"

[[mixins]]
config="lumin-graphics-mc-262.mixins.json"

[[dependencies.lumin_graphics_mc]]
modId="neoforge"
type="required"
versionRange="[26.2.0.37-beta]"
ordering="NONE"
side="CLIENT"

[[dependencies.lumin_graphics_mc]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="CLIENT"
