apply plugin: 'java-library'
apply plugin: 'net.neoforged.moddev'

dependencies {
    api project(':bridge-contract')
    api platform(libs.lumin.bom)
    api libs.lumin.core
    api libs.lumin.render
}

configurations {
    commonJava { canBeResolved = false; canBeConsumed = true }
    commonResources { canBeResolved = false; canBeConsumed = true }
}
artifacts {
    commonJava file('src/main/java')
    commonResources file('src/main/resources')
}
