[versions]
java = "25"
loom = "1.15.5"
moddev = "2.0.140"
minecraft-2612 = "26.1.2"
fabric-loader-2612 = "0.19.2"
fabric-api-2612 = "0.150.0+26.1.2"
neoform-2612 = "26.1.2-1"
neoforge-2612 = "26.1.2.76"
minecraft-262 = "26.2"
fabric-loader-262 = "0.19.3"
fabric-api-262 = "0.156.0+26.2"
neoform-262 = "26.2-2"
neoforge-262 = "26.2.0.37-beta"
lumin = "1.1.0-SNAPSHOT"
junit = "5.13.4"
junit-platform = "1.13.4"

[libraries]
lumin-bom = { module = "com.github.slmpc.lumingraphics:lumin-graphics-bom", version.ref = "lumin" }
lumin-core = { module = "com.github.slmpc.lumingraphics:lumin-graphics-core" }
lumin-render = { module = "com.github.slmpc.lumingraphics:lumin-graphics-render" }
minecraft-2612 = { module = "com.mojang:minecraft", version.ref = "minecraft-2612" }
fabric-loader-2612 = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader-2612" }
fabric-api-2612 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-2612" }
minecraft-262 = { module = "com.mojang:minecraft", version.ref = "minecraft-262" }
fabric-loader-262 = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader-262" }
fabric-api-262 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-262" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
