generated.sources.sha256=5553dd93ddc852fefab2349aae509ba3e65cbc78f0c35945822767efd8774b32
minecraft.version=26.2
origin.artifact=net.neoforged:neoform:26.2-2@zip
origin.sha256=09fd01e2371a94c78bc4d0d28645ab88206fcef395795182cee841765ebd5a63
origin.url=https://maven.neoforged.net/releases/net/neoforged/neoform/26.2-2/neoform-26.2-2.zip
type.CommandEncoder.sha256=3c03365b860001803f8d75066c029df520432773642b39cc58192f401ae727e8
type.CommandEncoder.signature=com.mojang.blaze3d.systems.CommandEncoder|fields=5|constructors=1|methods=27
type.CommandEncoder.source=com/mojang/blaze3d/systems/CommandEncoder.java
type.CompiledRenderPipeline.sha256=7bf2f61cd1af5e719983dee8c6f12a397fcb868bdc7decbd8f1e7f497aee58be
type.CompiledRenderPipeline.signature=com.mojang.blaze3d.pipeline.CompiledRenderPipeline|fields=0|constructors=0|methods=1
type.CompiledRenderPipeline.source=com/mojang/blaze3d/pipeline/CompiledRenderPipeline.java
type.GlBuffer.sha256=d3e83a0ea0aa2ae5c3576a996ccec5f9a5ffe7ce393f3cf119e2806e5129fa1e
type.GlBuffer.signature=com.mojang.blaze3d.opengl.GlBuffer|fields=4|constructors=1|methods=2
type.GlBuffer.source=com/mojang/blaze3d/opengl/GlBuffer.java
type.GlDevice.sha256=7de4cc475314a5d8acef1dfa0cc9e27471666d944a58fd01b89dc4969830c9a8
type.GlDevice.signature=com.mojang.blaze3d.opengl.GlDevice|fields=22|constructors=1|methods=28
type.GlDevice.source=com/mojang/blaze3d/opengl/GlDevice.java
type.GlProgram.sha256=e474d044c69cebf4d4d9d18d97967fc30a44bf819f991ed1b04ff7d33ffcfcad
type.GlProgram.signature=com.mojang.blaze3d.opengl.GlProgram|fields=6|constructors=1|methods=8
type.GlProgram.source=com/mojang/blaze3d/opengl/GlProgram.java
type.GlRenderPipeline.sha256=7b8d0f074452e2bedfdccbcd5566d6335eefb756ab5b07da497af92bc9faf421
type.GlRenderPipeline.signature=com.mojang.blaze3d.opengl.GlRenderPipeline|fields=2|constructors=0|methods=1
type.GlRenderPipeline.source=com/mojang/blaze3d/opengl/GlRenderPipeline.java
type.GlShaderModule.sha256=0a97caee4753e83000aee660906e9081644af3c84e94b14a4288502f161720f2
type.GlShaderModule.signature=com.mojang.blaze3d.opengl.GlShaderModule|fields=5|constructors=1|methods=4
type.GlShaderModule.source=com/mojang/blaze3d/opengl/GlShaderModule.java
type.GlTexture.sha256=16f003929566ac5c67aa67fbff4b313e43b066ea82701a1e9329d004056f0a3e
type.GlTexture.signature=com.mojang.blaze3d.opengl.GlTexture|fields=6|constructors=1|methods=9
type.GlTexture.source=com/mojang/blaze3d/opengl/GlTexture.java
type.GlTextureView.sha256=8622803e5615fdfa227cea85556081a545a7de2f9817d3ba7dbc24e2e0026788
type.GlTextureView.signature=com.mojang.blaze3d.opengl.GlTextureView|fields=4|constructors=1|methods=7
type.GlTextureView.source=com/mojang/blaze3d/opengl/GlTextureView.java
type.GpuBuffer.sha256=86dab7a805dbf23d4b459f237dcbaa7e2cb8257e7c588fb36a8e252534955233
type.GpuBuffer.signature=com.mojang.blaze3d.buffers.GpuBuffer|fields=13|constructors=1|methods=8
type.GpuBuffer.source=com/mojang/blaze3d/buffers/GpuBuffer.java
type.GpuDevice.sha256=bf49aeb4af8b69b782a1fb1a888a94e13642ac88c880ec5248179948bd435594
type.GpuDevice.signature=com.mojang.blaze3d.systems.GpuDevice|fields=3|constructors=1|methods=21
type.GpuDevice.source=com/mojang/blaze3d/systems/GpuDevice.java
type.GpuTexture.sha256=e16c1fada6501b5dd28ada5a8f3cd2583b8e933896ef32b02dd8bb04c6af42af
type.GpuTexture.signature=com.mojang.blaze3d.textures.GpuTexture|fields=12|constructors=1|methods=9
type.GpuTexture.source=com/mojang/blaze3d/textures/GpuTexture.java
type.GpuTextureView.sha256=10415538c64f88d206a9bd89683074ad2b8f8aae9209ce5b30729ad64508e73b
type.GpuTextureView.signature=com.mojang.blaze3d.textures.GpuTextureView|fields=3|constructors=1|methods=7
type.GpuTextureView.source=com/mojang/blaze3d/textures/GpuTextureView.java
type.RenderPass.sha256=67a3e1d2fbe44fd52bec05ff4200f70a06de131370f47a008109af0dea2c27b2
type.RenderPass.signature=com.mojang.blaze3d.systems.RenderPass|fields=10|constructors=1|methods=21
type.RenderPass.source=com/mojang/blaze3d/systems/RenderPass.java
type.RenderPipeline.sha256=9331f7d8ed792d92db0411e545694eb1971e7a625eac03e77a2ae34f9f29cc48
type.RenderPipeline.signature=com.mojang.blaze3d.pipeline.RenderPipeline|fields=13|constructors=1|methods=18
type.RenderPipeline.source=com/mojang/blaze3d/pipeline/RenderPipeline.java
type.RenderSystem.sha256=ec730c9a621d8f888a3d4552074933131a55ce55fc488c4849581ef38ef2bdce
type.RenderSystem.signature=com.mojang.blaze3d.systems.RenderSystem|fields=25|constructors=0|methods=36
type.RenderSystem.source=com/mojang/blaze3d/systems/RenderSystem.java
